<?php require_once 'router.php';?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  
    <title>TUDAI - CSR TodoList</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="">TUDAI CSR TodoList</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav d-flex">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="">Home</a>
                  </li>
                 </ul>
              </div>
            </div>
          </nav>
    </header>

    <!-- inicio main container -->
    <main class="container">

        <!-- formulario de alta de tarea -->
        <form id="task-form" method="POST" class="my-4">
            <div class="row">
                <div class="col-9">
                    <div class="form-group">
                        <label>nombre</label>
                        <input name="nombre" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>apellido</label>
                        <input name="apellido" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>nombre_producto</label>
                        <input name="nombre_producto" type="text" class="form-control">
                    </div>
                    <div class="form-group">
                        <label>tipoProducto</label>
                        <input name="tipoProducto" type="text" class="form-control">
                    </div>
                    
                </div>

               

            <button type="submit" class="btn btn-primary mt-2">Guardar</button>
        </form>

        <!-- lista de tareas -->
        <ul id="task-list" class="list-group">
           <!-- aca van a ir las tareas desde JS -->
        </ul>

        <!-- contador tareas -->
        <p class="mt-2"><small>Mostrando <span id="count">0</span> tareas</small></p>

    </main>
    <!-- fin main container -->

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
<script src="js/app.js"></script>
</body>
</html>
